import { AgeRating, Genre, Prisma } from '@prisma/client';

export const MOVIES: Prisma.MovieCreateManyInput[] = [
  {
    title: 'Все везде и сразу',
    genres: [Genre.Comedy],
    releaseDate: new Date('2024-05-19'),
    price: 49.99,
    rating: 9.5,
    ageRating: AgeRating.E,
    developer: 'CD Project',
    publisher: 'CD Project',
    image: '220x330.webp',
  },
  {
    title: 'Я легенда',
    genres: [Genre.Thriller],
    releaseDate: new Date('2016-05-20'),
    price: 49.99,
    rating: 7.5,
    ageRating: AgeRating.E,
    developer: 'Acame',
    publisher: 'Acame',
    image: '588.png',
  },
  {
    title: '2012',
    genres: [Genre.Comedy],
    releaseDate: new Date('2011-02-19'),
    price: 19.99,
    rating: 9.0,
    ageRating: AgeRating.T,
    developer: 'Futire Stidios',
    publisher: 'Futire Stidios',
    image: '2012_Poster.jpg',
  },
  {
    title: 'Иные',
    genres: [Genre.Horror],
    releaseDate: new Date('2015-02-10'),
    price: 29.99,
    rating: 6.0,
    ageRating: AgeRating.E,
    developer: 'Stidios',
    publisher: 'Stidios',
    image: '2018_film.jpg',
  },
  {
    title: 'Карате пацан',
    genres: [Genre.Action],
    releaseDate: new Date('2014-08-10'),
    price: 10.99,
    rating: 9.8,
    ageRating: AgeRating.AO,
    developer: 'Worners',
    publisher: 'Worners',
    image: '1631693-5669299.jpg',
  },
  {
    title: 'Хранители',
    genres: [Genre.Fantasy],
    releaseDate: new Date('2022-03-06'),
    price: 69.99,
    rating: 8.0,
    ageRating: AgeRating.AO,
    developer: 'LKS',
    publisher: 'LKS',
    image: 'Watchmen_Poster_Final.jpg',
  },
];
