import { AgeRating, Genre, Prisma } from '@prisma/client';

export const MOVIES: Prisma.MovieCreateManyInput[] = [
  {
    title: 'Все везде и сразу',
    genres: [Genre.Comedy],
    releaseDate: new Date('2024-05-19'),
    price: 49.99,
    rating: 9.5,
    ageRating: AgeRating.E,
    developer: 'CD Project',
    publisher: 'CD Project',
    image: '220x330.webp',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: 'Я легенда',
    genres: [Genre.Thriller],
    releaseDate: new Date('2016-05-20'),
    price: 49.99,
    rating: 7.5,
    ageRating: AgeRating.AO,
    developer: 'Acame',
    publisher: 'Acame',
    image: '588.png',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: '2012',
    genres: [Genre.Comedy, Genre.Action],
    releaseDate: new Date('2011-02-19'),
    price: 19.99,
    rating: 9.0,
    ageRating: AgeRating.T,
    developer: 'Futire Stidios',
    publisher: 'Futire Stidios',
    image: '2012_Poster.jpg',
    discountPrice: 11.99,
  },
  {
    title: 'Иные',
    genres: [Genre.Horror, Genre.Thriller],
    releaseDate: new Date('2015-02-10'),
    price: 29.99,
    rating: 6.0,
    ageRating: AgeRating.E,
    developer: 'Stidios',
    publisher: 'Stidios',
    image: '2018_film.jpg',
    discountPrice: 19.99,
  },
  {
    title: 'Карате пацан',
    genres: [Genre.Action],
    releaseDate: new Date('2014-08-10'),
    price: 10.99,
    rating: 9.8,
    ageRating: AgeRating.E,
    developer: 'Worners',
    publisher: 'Worners',
    image: '1631693-5669299.jpg',
    discountPrice: 39.99,
  },
  {
    title: 'Хранители',
    genres: [Genre.Fantasy],
    releaseDate: new Date('2022-03-06'),
    price: 69.99,
    rating: 8.0,
    ageRating: AgeRating.E,
    developer: 'LKS',
    publisher: 'LKS',
    image: 'Watchmen_Poster_Final.jpg',
    discountPrice: 39.99,
  },
  {
    title: 'Covenant',
    genres: [Genre.Fantasy, Genre.Thriller],
    releaseDate: new Date('2021-08-06'),
    price: 56.99,
    rating: 6.0,
    ageRating: AgeRating.AO,
    developer: 'LKSFJ',
    publisher: 'LKSFJ',
    image: 'covenant.webp',
    discountPrice: 39.99,
  },
  {
    title: 'Dark Wordl',
    genres: [Genre.Fantasy, Genre.Thriller],
    releaseDate: new Date('2016-08-06'),
    price: 19.99,
    rating: 4.0,
    ageRating: AgeRating.E,
    developer: 'Gorka',
    publisher: 'Gorka',
    image: 'darkworld.jpg',
    discountPrice: 10.99,
  },
  {
    title: 'Dark World',
    genres: [Genre.Fantasy],
    releaseDate: new Date('2011-01-12'),
    price: 49.99,
    rating: 9.0,
    ageRating: AgeRating.AO,
    developer: 'GorStudio',
    publisher: 'GorStudio',
    image: 'prototype.jpg',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: 'Shark',
    genres: [Genre.Thriller],
    releaseDate: new Date('2017-01-14'),
    price: 79.99,
    rating: 9.3,
    ageRating: AgeRating.AO,
    developer: 'Astudio',
    publisher: 'Astudio',
    image: 'shark.jpeg',
    discountPrice: 39.99,
  },
  {
    title: 'Yensday',
    genres: [Genre.Comedy],
    releaseDate: new Date('2025-01-14'),
    price: 69.99,
    rating: 9.9,
    ageRating: AgeRating.E,
    developer: 'Vivas',
    publisher: 'Vivas',
    image: 'yensday.jpeg',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: 'Flays',
    genres: [Genre.Action],
    releaseDate: new Date('2018-01-14'),
    price: 49.99,
    rating: 3.3,
    ageRating: AgeRating.T,
    developer: 'Astudio',
    publisher: 'Astudio',
    image: 'shark.jpeg',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: 'Yensday2',
    genres: [Genre.Comedy],
    releaseDate: new Date('2025-08-20'),
    price: 89.99,
    rating: 9.4,
    ageRating: AgeRating.E,
    developer: 'Vivas',
    publisher: 'Vivas',
    image: 'yensday.jpeg',
    discountPrice: 39.99,
  },
  {
    title: 'House',
    genres: [Genre.Action],
    releaseDate: new Date('2021-08-20'),
    price: 39.99,
    rating: 7.4,
    ageRating: AgeRating.E,
    developer: 'Vivas',
    publisher: 'Vivas',
    image: 'prototype.jpg',
    discountPrice: 29.99,
  },
  {
    title: 'Venera',
    genres: [Genre.Comedy],
    releaseDate: new Date('2013-08-20'),
    price: 49.99,
    rating: 7.4,
    ageRating: AgeRating.E,
    developer: 'Vivas',
    publisher: 'Vivas',
    image: 'prototype.jpg',
    discountPrice: 39.99,
    isHasSecondDiscount: true,
  },
  {
    title: 'LaCasaDePeper',
    genres: [Genre.Action],
    releaseDate: new Date('2019-08-20'),
    price: 29.99,
    rating: 7.4,
    ageRating: AgeRating.E,
    developer: 'Vivas',
    publisher: 'Vivas',
    image: 'darkworld.jpg',
    discountPrice: 19.99,
  },
];
